### ISSUE TITLE
Video fikirleri

### ISSUE THREAD

**Issue by fatihacet** [fatihacet/youtube#1]
Kanalda yayinlamayi dusundugum bir cok video var ve bunlari sirada bekletiyorum. Video cekmek istedigim zaman listeye bakip, bir konu secip videoyu cekip yayinliyorum.

Bu issue'da listemde olan her bir videoyu yeni bir comment olarak ekleyecegim. Kanalda yayinlanmasini istediginiz videolara 👍  eklerseniz, yeni video cekerken en cok 👍  alan videoyu cekip onu yayinlamis olurum. Bu sayede en cok merak edilen konular hakkinda videolar gecikmez.

Degisik bir video fikriniz varsa, yeni bir issue acip belirtirseniz cok sevinirim.

Tesekkurler :+1: 👋

**Comment by fatihacet** [comment]
### GitHub ve GitLab nedir?

Ne Nedir? serisi icin GitHub ve GitLab'in ne oldugundan, neden kullandigimizdan ve iki proje arasindaki farklardan bahsetmeyi dusundugum bir video.

**Comment by fatihacet** [comment]
### CI/CD nedir?

Ne Nedir? serisi icin Continuous Integration ve Continuous Delivery kavramlarinin ne oldugunu, neden kullandigimizi, bize nasil yardimci olduklarindan bahsetmeyi dusundugum bir video.

**Comment by fatihacet** [comment]
### ✅  Kod review nedir ve neden yapilir?

Kod review nedir, neden yapilir, onemi nedir gibi konulardan bahsetmeyi dusundugum bir video.

[![https://i.ytimg.com/vi/ZQYLEt-hCb4/maxresdefault.jpg](https://i.ytimg.com/vi/ZQYLEt-hCb4/maxresdefault.jpg)](https://www.youtube.com/watch?v=ZQYLEt-hCb4&list=PLa3NvhdFWNir3h-MGZvcZJNAq2qhEF1Bu&index=11)

**Comment by fatihacet** [comment]
### ✅ Yeniden yazmak mi duzeltme yapmak mi? (Refactor vs Rewrite)

Var olan bir projeyi ya da ozelligi ne zaman yeniden yazmaliyiz ne zaman icine girip iyilestirme yapmaliyiz gibi sorulardan bahsetmeyi dusundugum bir video.


[![cover](https://i.ytimg.com/vi/O-IF-EnwscA/maxresdefault.jpg)](https://www.youtube.com/watch?v=O-IF-EnwscA)

**Comment by fatihacet** [comment]
### Alayli ve Mektepli olayi

Alayli olmak ile mektepli olmanin arasindaki farklardan bahsetmeyi dusundugum bir video.

**Comment by fatihacet** [comment]
### Teknoloji secimi

Yeni bir projeye baslayacagiz ya da yeni bir sey ogrenecegiz diyelim hangisini ogrenelim, kullanacagimiz teknolojileri nasil secelim, kullandigimiz teknolojiler neden onemlidir gibi sorulardan bahsetmeyi dusundugum bir video.

**Comment by fatihacet** [comment]
### Frontend mi? Backend mi? Yoksa Full Stack mi?

Frontend developer kimdir konusunu anlattim. Peki Frontend developer olmak mi yoksa Backend developer mi hatta Full Stack developer mi konusunu konusmayi dusundugum bir video.

**Comment by fatihacet** [comment]
### Unvan (title) mevzusu

Title nedir, nasil alinir, kim bize title verir, Sr. ne zaman olunur gibi title ile ilgili bir cok konudan bahsetmeyi dusundugum bir video.

**Comment by fatihacet** [comment]
### Turkce Kaynaklar

Turkce kaynak bulmak ve Turkce kaynak ile ogrenmek hakkinda konusmayi dusundugum bir video.

**Comment by fatihacet** [comment]
###  ✅  Uzaktan calismak icin is bulmak

Uzaktan calisilacak bir isi nereden buluruz, uzaktan calismak icin hangi yetilere sahip olmaliyiz gibi sorulardan bahsetmeyi dusundugum bir video.

[![https://i.ytimg.com/vi/mXs1ievO6Ao/maxresdefault.jpg](https://i.ytimg.com/vi/mXs1ievO6Ao/maxresdefault.jpg)](https://www.youtube.com/watch?v=mXs1ievO6Ao&index=1&list=PLa3NvhdFWNioPEmCLB1lhhbOLj2PyLUW9)

**Comment by fatihacet** [comment]
### Kullandigim editor ve editor ayarlarim

Hangi editoru neden kullandigim ve nasil kullandigim hakkinda konusmayi dusundugum bir video.

**Comment by fatihacet** [comment]
### Calisma odam

Calisma odami gosterip kullandigim donanimlari anlattigim bir video.

**Comment by fatihacet** [comment]
### Mac OS ipuclari

Mac OS'da kendimce kullandigim bir cok yararli ve isimi kolaylastiran arac, kisayol ya da ozellik var. Bunlardan bahsetmeyi dusundugum bir video.

**Comment by fatihacet** [comment]
### Uzaktan calismak icin mulakat surecleri

Uzaktan bir is bulmak istediginiz zaman nasil bir mulakat sureci sizi bekliyor, mulaktlar ne kadar suruyor gibi konulardan bahsetmeyi dusundugum bir video.

**Comment by fatihacet** [comment]
### JavaScript cok re re ro

`[] + []` yaptim `''` dondu, hahaha!!111 bu JS cok dandik dil yeaa.

_Sektor Linc Istiyor Fatih Acet Edition_

**Comment by fatihacet** [comment]
### Kutu oyunlari

Kutu oyunlari oynamayi ailecek cok seviyoruz ve evimde guzel bir koleksiyonum var. Kutu oyunlarindan bahsetmeyi dusundugum bir video.

**Comment by fatihacet** [comment]
### ✅  Kahve

[![https://i.ytimg.com/vi/_Adh-vnGegw/maxresdefault.jpg](https://i.ytimg.com/vi/_Adh-vnGegw/maxresdefault.jpg)](https://www.youtube.com/watch?v=_Adh-vnGegw)

Random Access Muhabbetler playlist'i icin kahve uzerine konusacagim bir video. Suan kullandigim espresso makinesi, daha once kullandigim AeroPress ve kahveyi nasil tedarikler ettigim hakkinda bir video.

**Comment by incendies** [comment]
Debug, Bugfix sırasındaki yararlı olabilecek adımlar ?

**Comment by fatihacet** [comment]
@incendies yorumunu sildim ve bu issue'yu tartismaya kapadim :) Buranin sadece oylama icin kullanilmasini istiyorum. Tavsiyen icin bir issue acar misin, kusura bakma.

Birazdan bu yorumu da silecegim :)
