### ISSUE TITLE
Google Cloud Platform: Nasıl sunucu oluşturulur ?

### ISSUE THREAD

**Issue by erhanpaker** [fatihacet/youtube#3]
Google Cloud ilgili çok fazla türkçe kaynak yok,  Google Cloud Platform: Google Cloud Computing ile nasıl proje oluşturlur, wordpress nasıl kurulur vs.  bir video serisi olsa güzel olur  https://cloud.google.com/

**Comment by fatihacet** [comment]
GCP ile ilgili cok deneyimim olmadigi icin boyle bir video cekmem cok dogru olmaz sanirim. Tesekkurler.
